### ISSUE TITLE
Add type for caches.default

### ISSUE THREAD

**Issue by emillime** [EverlastingBugstopper/worker-typescript-template#8]
What is the best way to add the property default on type CacheStorage? It would be nice if this template added it.
If you try to use it right now you get an error saying: 

> Property 'default' does not exist on type 'CacheStorage'.

**Comment by emillime** [comment]
Maybe it's enough to just add this.
`declare global {
  const myKVNamespace: KVNamespace;

  interface CacheStorage {
    default: CacheStorage;
  }
}`

**Comment by EverlastingBugstopper** [comment]
Hi! Thanks for checking out this template - I'm going to close this issue as it needs to be resolved in @cloudflare/workers-types (seems like you found an issue there as well 😄) https://github.com/cloudflare/workers-types/issues/8
